#!/usr/bin/env python3

import csv
import os, sys, argparse

parser = argparse.ArgumentParser(description='Optional app description')
parser.add_argument('-i', '--infile', required = True, type=str, help='The combined clone file generated by mixcr')
parser.add_argument('-o', '--outfile', required = True, type=str, help='The name of the output file')

args = parser.parse_args()

in_file=args.infile
out_file = args.outfile

clone_count_dic = {}

with open(in_file) as i:
  header = i.readline().strip().split('\t')
  n_fields = len(header)
  for line in i: 
    info = line.strip().split('\t')
    info_dic = { header[n] : info[n] for n in range(0, n_fields)}
    n_seq = info_dic['nSeqComplete']
    if n_seq not in clone_count_dic :
      clone_count_dic[n_seq] = 1 
    else:
      clone_count_dic[n_seq] += 1

#print(":".join(header))

with open(in_file) as i, open(out_file, 'w') as o:
  header = i.readline().strip().split('\t')
  n_fields = len(header)
  o.write('\t'.join(header) + '\tclonePlateFreq\n')        
  
  for line in i : 
    info = line.strip().split('\t')
    info_dic = { header[n] : info[n] for n in range(0, n_fields)} 
    n_seq = info_dic['nSeqComplete']
    f = clone_count_dic[n_seq]
    o.write('\t'.join(info) + '\t' + str(f) + '\n')
